baseURL = "http://example.com"
languageCode = "en-us"
title = "My Site"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""

[Params]
    tagline = "The Tagline"
    description = "Description of site"
    logoBig = "images/logo-big.png"
    logoSmall = "images/logo-small.png"
    favicon = "favicon.ico"
    opengraphImage = "images/image.png"
    twitter = ""
    linkedin = ""
    github = ""
    email = ""
    googleTagManager = ""
    highlightJS = false
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "About"
    url = "/#about"
    weight = 1

[[menu.main]]
    name = "Our Work"
    url = "/#our-work"
    weight = 2

[[menu.main]]
    name = "Connect"
    url = "/#connect"
    weight = 3

